version: "2.29.6"
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: clinic_mysql
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: clinic_frontend
        ports:
            - '8091:8091'
        depends_on:
            - backend
    backend:
        build:
            context: ../
            dockerfile: backend/Dockerfile
        container_name: clinic_backend
        restart: on-failure
        depends_on:
            - db
        environment:
            mysql_host: "clinic_mysql"
            mysql_port: '3306'
        ports:
            - '8090:8090'
        links:
            - db
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: clinic_nginx
        ports:
            - '80:80'
            - '8080:8080'
        depends_on:
            - backend
            - frontend
