version: "3.7"
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: clinic_mysql
        ports:
            - '3307:3306'
        volumes:
            - /opt/docker-volumes/clinic/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
#    frontend:
#        build:
#            context: ../frontend
#            dockerfile: Dockerfile
#        container_name: clinic_frontend
#        command: npm run start
#        ports:
#            - '8091:8091'
#        volumes:
#            - /opt/docker-volumes/clinic/frontend:/front
#            - /front/node_modules
#        depends_on:
#            - backend
    backend:
        build:
            context: ../
            dockerfile: backend/Dockerfile
        container_name: clinic_backend
        restart: on-failure
        depends_on:
            - db
        ports:
            - '8090:8090'
        command: mvn spring-boot:run
        links:
            - db
    nginx:
        image: nginx:1.14
        container_name: clinic_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
            - '8080:8080'