version: "2"
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: clinic_mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: clinic_frontend
        ports:
            - '8091:8091'
        depends_on:
            - backend
    backend:
        build:
            context: ../
            dockerfile: backend/Dockerfile
        container_name: clinic_backend
        restart: always
        depends_on:
            - db
        ports:
            - '8090:8090'
        links:
            - db
    nginx:
        image: nginx:1.14
        container_name: clinic_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
            - '8080:8080'
        depends_on:
            - backend
            - frontend