version: "2.1"
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: docker_mysql_latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: localhost
        healthcheck:
            test: "/usr/bin/mysql --user=testuser --password=testpass --execute \"SHOW DATABASES;\""
            interval: 10s
            timeout: 5s
            retries: 5
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: clinic_frontend
        ports:
            - '8091:8091'
        depends_on:
            - backend
    backend:
        build:
            context: ../
            dockerfile: backend/Dockerfile
        container_name: clinic_backend
        restart: always
        depends_on:
            db:
                condition: "service_healthy"
        environment:
            mysql_host: "docker_mysql_latest"
        ports:
            - '8090:8090'
        links:
            - db
    nginx:
        image: nginx:1.14
        container_name: clinic_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
            - '8080:8080'
        depends_on:
            - backend
            - frontend