package by.gp.clinic.enumerated;

public enum Speciality {

    PSYCHIATRIST,
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    OPHTHALMOLOGIST,
    OTOLARYNGOLOGIST,
    PULMONOLOGIST,
    THERAPIST,
    PATHOLOGYST
}
